# Generated by Django 3.0.5 on 2020-04-25 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200424_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 2, 11, 35, 252105)),
        ),
    ]
