# Generated by Django 3.0.5 on 2020-04-25 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200425_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='list_skils_needed',
            new_name='skills_required',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(
                default=datetime.datetime(2020, 4, 25, 4, 21, 35, 354430)),
        ),
    ]
