# Generated by Django 3.0.5 on 2020-04-27 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200425_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 16, 27, 26, 686547)),
        ),
    ]
