# Generated by Django 3.0.5 on 2020-04-27 19:58

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200427_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 19, 58, 44, 315978)),
        ),
    ]
