# Generated by Django 3.0.5 on 2020-05-07 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200427_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 18, 25, 12, 682771)),
        ),
    ]
