# Generated by Django 3.0.5 on 2020-05-18 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200518_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 21, 5, 6, 852959)),
        ),
    ]
