# Generated by Django 3.0.5 on 2020-05-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200529_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client_username',
        ),
        migrations.AddField(
            model_name='project',
            name='owner_username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
