# Generated by Django 3.0.5 on 2020-06-02 16:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200529_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='user',
            name='may_interested',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None),
        ),
    ]
