# Generated by Django 3.0.5 on 2020-06-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200602_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='collaborator_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='completed_works',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='outstanding_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='recomended',
            field=models.IntegerField(default=0),
        ),
    ]
