# Generated by Django 3.0.5 on 2020-06-10 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('api', '0022_rating'), ('api', '0023_auto_20200609_2011'), ('api', '0024_auto_20200609_2109'), ('api', '0025_remove_user_outstanding_user'), ('api', '0026_auto_20200610_1359')]

    dependencies = [
        ('api', '0021_auto_20200608_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='client_rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='collaborator_rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='completed_works',
        ),
        migrations.RemoveField(
            model_name='user',
            name='outstanding_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='recomended',
        ),
        migrations.AddField(
            model_name='user',
            name='completed_works',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='recomended',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('rating_type', models.CharField(max_length=50)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'unique_together': {('rating_type', 'project')},
            },
        ),
    ]
