# Generated by Django 3.0.5 on 2020-06-10 22:00

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('api', '0023_service'), ('api', '0024_auto_20200610_2115'), ('api', '0025_auto_20200610_2129'), ('api', '0026_auto_20200610_2131'), ('api', '0027_auto_20200610_2134')]

    dependencies = [
        ('api', '0022_rating_squashed_0026_auto_20200610_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='project',
            name='end_postulations',
            field=models.DateField(default=datetime.date(2020, 6, 17)),
        ),
        migrations.AddField(
            model_name='project',
            name='work_modality',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1500)),
                ('work_modality', models.CharField(max_length=500)),
                ('experience', models.CharField(max_length=1500)),
                ('availability', models.CharField(max_length=1500)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, null=True, size=None)),
                ('skills_required', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, null=True, size=None)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_price_range', models.IntegerField(default=0)),
                ('max_price_range', models.IntegerField(default=0)),
                ('status', models.CharField(default='published', max_length=30)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='collaborator_id',
            field=models.IntegerField(null=True),
        ),
    ]
