# Generated by Django 3.0.5 on 2020-06-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200611_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='experience_required',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
