# Generated by Django 3.0.5 on 2020-06-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200612_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('published', 'published'), ('in_progress', 'in_progress'), ('selection', 'selection')], default='published', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='work_modality',
            field=models.CharField(choices=[('fulltime', 'fulltime'), ('parttime', 'parttime'), ('mixed', 'mixed'), ('homeoffice', 'homeoffice')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('published', 'published'), ('in_progress', 'in_progress'), ('selection', 'selection')], default='published', max_length=30),
        ),
        migrations.AlterField(
            model_name='service',
            name='work_modality',
            field=models.CharField(choices=[('fulltime', 'fulltime'), ('parttime', 'parttime'), ('mixed', 'mixed'), ('homeoffice', 'homeoffice')], max_length=500),
        ),
    ]
