# Generated by Django 3.0.5 on 2020-06-15 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200612_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='receiver',
        ),
        migrations.AlterField(
            model_name='project',
            name='end_postulations',
            field=models.DateField(default=datetime.date(2020, 6, 22)),
        ),
    ]
