# Generated by Django 3.0.5 on 2020-06-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200615_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('acepted', 'acepted'), ('rejected', 'rejected')], default='created', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('emitter', 'project')},
        ),
    ]
