# Generated by Django 3.0.5 on 2020-06-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20200616_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='requirements',
            field=models.CharField(default='R', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='why_you',
            field=models.CharField(default='soy bacan', max_length=1500),
            preserve_default=False,
        ),
    ]
