# Generated by Django 3.0.5 on 2020-06-19 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20200617_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner_username',
        ),
        migrations.RemoveField(
            model_name='service',
            name='owner_username',
        ),
        migrations.AlterField(
            model_name='project',
            name='end_postulations',
            field=models.DateField(default=datetime.date(2020, 6, 26)),
        ),
    ]
