# Generated by Django 3.0.5 on 2020-06-24 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20200623_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='invited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='modified_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_postulations',
            field=models.DateField(default=datetime.date(2020, 7, 1)),
        ),
    ]
