# Generated by Django 3.0.5 on 2020-06-24 16:04

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20200624_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, null=True, size=None)),
                ('prices', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, null=True, size=None)),
                ('accepted', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=1000)),
                ('number_stages', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_emitter', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_project', to='api.Project')),
            ],
        ),
    ]
