# Generated by Django 3.0.5 on 2020-06-26 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20200626_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_picture', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='picture',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_picture', to='api.Project'),
        ),
        migrations.AddField(
            model_name='picture',
            name='type',
            field=models.CharField(default='picture', max_length=250),
        ),
    ]
