# Generated by Django 3.0.5 on 2020-07-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20200701_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_image',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='service',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
