# Generated by Django 3.0.5 on 2020-07-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20200707_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='follower',
            new_name='owner',
        ),
    ]
