# Generated by Django 3.0.5 on 2020-07-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20200707_1917'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('owner', 'following')},
        ),
    ]
