# Generated by Django 3.0.5 on 2020-07-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20200713_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='file',
        ),
        migrations.AddField(
            model_name='picture',
            name='url_in_storage',
            field=models.CharField(default='s', max_length=250),
            preserve_default=False,
        ),
    ]
