# Generated by Django 3.0.5 on 2020-07-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20200713_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='url_in_storage',
            new_name='path_in_storage',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='url',
            new_name='storage_url',
        ),
    ]
