# Generated by Django 3.0.5 on 2020-07-14 19:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20200713_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_postulations',
            field=models.DateField(default=datetime.date(2020, 7, 21)),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_type', models.CharField(choices=[('project', 'project'), ('request-collaborator', 'request-collaborator'), ('service', 'service')], max_length=50)),
                ('text_number', models.IntegerField()),
                ('class_type', models.CharField(choices=[('project', 'project'), ('request', 'request'), ('service', 'service'), ('user', 'user')], max_length=50)),
                ('class_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
