# Generated by Django 3.0.5 on 2020-07-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20200715_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('published', 'published'), ('in_progress', 'in_progress'), ('selection', 'selection'), ('payment', 'payment')], default='published', max_length=30),
        ),
    ]
