# Generated by Django 3.0.5 on 2020-07-22 15:26

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20200720_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='payment_completed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='proposal',
            name='stage_completed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_postulations',
            field=models.DateField(default=datetime.date(2020, 7, 29)),
        ),
    ]
