# Generated by Django 3.0.5 on 2020-07-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20200723_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectjournal',
            name='entry',
        ),
    ]
