# Generated by Django 3.0.5 on 2020-07-24 15:01

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_remove_projectjournal_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_postulations',
            field=models.DateField(default=datetime.date(2020, 7, 31)),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills_required',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='service',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='service',
            name='skills_required',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, size=None),
        ),
    ]
