# Generated by Django 3.0.5 on 2020-07-27 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20200724_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectjournal',
            name='entry',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_postulations',
            field=models.DateField(default=datetime.date(2020, 8, 3)),
        ),
    ]
