# Generated by Django 3.0.5 on 2020-07-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20200727_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='original_name',
            field=models.CharField(default='hola', max_length=250),
            preserve_default=False,
        ),
    ]
