# Generated by Django 3.0.5 on 2020-08-19 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20200819_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbcard',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_kanban', to='api.Project'),
            preserve_default=False,
        ),
    ]
