# Generated by Django 3.0.5 on 2020-08-24 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20200819_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstage',
            name='aproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_postulations',
            field=models.DateField(default=datetime.date(2020, 8, 31)),
        ),
    ]
