# Generated by Django 3.0.5 on 2020-08-26 14:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_auto_20200824_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='recovery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertoken',
            name='validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_postulations',
            field=models.DateField(default=datetime.date(2020, 9, 2)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_register', to=settings.AUTH_USER_MODEL),
        ),
    ]
