# Generated by Django 3.0.5 on 2020-08-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_auto_20200828_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating_putuality',
            new_name='rating_puntuality',
        ),
    ]
