# Generated by Django 3.0.5 on 2020-09-01 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_auto_20200901_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating_comunication',
            new_name='rating_communication',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='rating_puntuality',
            new_name='rating_punctuality',
        ),
    ]
